name: react test

on: 
  pull_request:
    types:
      opened
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
      - name: Check Vite version (debug)
        run: npx vite --version
      - name: Build project
        run: npx vite build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: Build project
        run: npx vite build
      - name: Clean up invalid files
        run: |
          find dist -type f -name '*:*' -exec rm -f {} +
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/ 
      - name: deploy
        run: echo "deploying proj"
